# --- QMIX ego-agent specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy_attack"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode_robust"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "qmix_attacker"

# --- Default Attacker specific parameters --- #
attacker: "mlp" # Default mlp agent
attacker_hidden_dim: 64 # Size of hidden dim for default mlp attacker
attack_mode: "action"
attacker_action_selector: "sparse"
attacker_soft_tau: 0.005
attacker_buffer_size: 1000 # small -> care recent trajs
local_results_path: "attack_results"